<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_PJiqMNLyEe2vSZc3OuTw8Q" name="MyDiagram" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_PJiqMdLyEe2vSZc3OuTw8Q" name="Pools">
      <elements xmi:type="process:Lane" xmi:id="_PJiqMtLyEe2vSZc3OuTw8Q" name="Cliente" actor="_PJiqS9LyEe2vSZc3OuTw8Q">
        <elements xmi:type="process:StartEvent" xmi:id="_PJiqM9LyEe2vSZc3OuTw8Q" name="Iniciar" outgoing="_PJiqSNLyEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PJiqNNLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PJiqNdLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PJiqNtLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5xZygNLyEe2vSZc3OuTw8Q" name="Ideia de projeto" outgoing="_DErUsNLzEe2vSZc3OuTw8Q" incoming="_PJiqSNLyEe2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PJiqONLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PJiqOdLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PJiqOtLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PJiqO9LyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PJiqPNLyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PJiqPdLyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PJiqPtLyEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PJiqP9LyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5xZyitLyEe2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_5xZyi9LyEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5xZyidLyEe2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5xZyjNLyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_-CgbUNLyEe2vSZc3OuTw8Q" name="Ideia de projeto base" outgoing="_VONs8NLzEe2vSZc3OuTw8Q" incoming="_DErUsNLzEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-CgbUtLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-CgbUdLyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-CgbU9LyEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-CgbVNLyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-CgbVdLyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-CgbVtLyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-CgbWNLyEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-CgbV9LyEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_rd9QINL0Ee2vSZc3OuTw8Q" name="Mensagem com requisitos pedidos pela empresa" outgoing="_fWkyINL1Ee2vSZc3OuTw8Q" incoming="_0TiwwNL0Ee2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rd9QItL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rd9QIdL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rd9QI9L0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rd9QJNL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rd9QJdL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rd9QJtL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rd9QKNL0Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rd9QJ9L0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_L9VskNL1Ee2vSZc3OuTw8Q" name="Providenciar informações" outgoing="_wm31QNL1Ee2vSZc3OuTw8Q" incoming="_fWkyINL1Ee2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L9VsktL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L9VskdL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L9Vsk9L1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_L9VslNL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_L9VsldL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_L9VsltL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_L9VsmNL1Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_L9Vsl9L1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_L9VsmtL1Ee2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_L9Vsm9L1Ee2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_L9VsmdL1Ee2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_L9VsnNL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_rYSQgNL1Ee2vSZc3OuTw8Q" name="Envio de informações" outgoing="_755osNL1Ee2vSZc3OuTw8Q" incoming="_wm31QNL1Ee2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rYS3kdL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rYS3kNL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rYS3ktL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rYS3k9L1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rYS3lNL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rYS3ldL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rYS3l9L1Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rYS3ltL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_KDtW0NMIEe2vSZc3OuTw8Q" name="Receber" outgoing="_P3nPINMIEe2vSZc3OuTw8Q" incoming="_Me7cENMIEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KDtW0tMIEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KDtW0dMIEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KDtW09MIEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KDtW1NMIEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KDtW1dMIEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KDtW1tMIEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KDtW2NMIEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KDtW19MIEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OyzjMNMIEe2vSZc3OuTw8Q" name="Fim" incoming="_P3nPINMIEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Oy0KQdMIEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Oy0KQNMIEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Oy0KQtMIEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_gJzGMNLyEe2vSZc3OuTw8Q" name="Empresa/Analistas">
        <elements xmi:type="process:ReceiveTask" xmi:id="_IDBeANLzEe2vSZc3OuTw8Q" name="Ideia de projeto base" outgoing="_yLYm4NLzEe2vSZc3OuTw8Q" incoming="_VONs8NLzEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IDBeAtLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IDBeAdLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IDBeA9LzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IDBeBNLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IDBeBdLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IDCFENLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IDCFEtLzEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IDCFEdLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rNGmINLzEe2vSZc3OuTw8Q" name="Analisar a viabilidade do projeto" outgoing="_RYmQ0NL0Ee2vSZc3OuTw8Q" incoming="_yLYm4NLzEe2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rNHNMdLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rNHNMNLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rNHNMtLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rNHNM9LzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rNHNNNLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rNHNNdLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rNHNN9LzEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rNHNNtLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_Hb5FMNL2Ee2vSZc3OuTw8Q" name="Entre 2 a 7 Dias"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rNHNOdLzEe2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_rNHNOtLzEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rNHNONLzEe2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rNHNO9LzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__ecYYNLzEe2vSZc3OuTw8Q" name="Definir a equipe de trabalho" outgoing="_MY77ENMDEe2vSZc3OuTw8Q" incoming="_TZkqENL0Ee2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8ff7AdLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8ff7ANLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8ff7AtLzEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8ff7A9LzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8ff7BNLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8ff7BdLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8ff7B9LzEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8ff7BtLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__ecYatLzEe2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="__ecYa9LzEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__ecYadLzEe2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__ecYbNLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_Khq1QNL0Ee2vSZc3OuTw8Q" name="Viavel ?" outgoing="_S2XPUNL0Ee2vSZc3OuTw8Q _TZkqENL0Ee2vSZc3OuTw8Q" incoming="_RYmQ0NL0Ee2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Khq1QtL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Khq1QdL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Khq1Q9L0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_NlOF0NL0Ee2vSZc3OuTw8Q" name="Fim" incoming="_S2XPUNL0Ee2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NlOs4dL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NlOs4NL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NlOs4tL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_daCCYNL0Ee2vSZc3OuTw8Q" name="Envio de mensagem com requisito de dados especificos do cliente" outgoing="_0TiwwNL0Ee2vSZc3OuTw8Q" incoming="_cXFiMNL1Ee2vSZc3OuTw8Q _veNRINMCEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_daCCYtL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_daCCYdL0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_daCCY9L0Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_daCCZNL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_daCCZdL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_daCCZtL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_daCCaNL0Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_daCCZ9L0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_W5R1sNL1Ee2vSZc3OuTw8Q" name="Identificar os dados necessários para o projeto" outgoing="_cXFiMNL1Ee2vSZc3OuTw8Q" incoming="_MY77ENMDEe2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_W5R1stL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_W5R1sdL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_W5R1s9L1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_W5R1tNL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_W5R1tdL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_W5R1ttL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_W5R1uNL1Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_W5R1t9L1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_W5R1utL1Ee2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_W5R1u9L1Ee2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_W5R1udL1Ee2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_W5R1vNL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_zqYCgNL1Ee2vSZc3OuTw8Q" name="Coletar informações " outgoing="_ckBVgNL2Ee2vSZc3OuTw8Q" incoming="_755osNL1Ee2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zqYCgtL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zqYCgdL1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zqYCg9L1Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zqYChNL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zqYChdL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zqYChtL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zqYCiNL1Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zqYCh9L1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Y7vAMNL2Ee2vSZc3OuTw8Q" name="Organização de dados" outgoing="_yT2hMNMFEe2vSZc3OuTw8Q _0HxV4NMFEe2vSZc3OuTw8Q" incoming="_rATicNMCEe2vSZc3OuTw8Q _xqskkNMHEe2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Y7vAMtL2Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Y7vAMdL2Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Y7vAM9L2Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Y7vANNL2Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Y7vANdL2Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Y7vANtL2Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Y7vAONL2Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Y7vAN9L2Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Y7vAOtL2Ee2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_Y7vAO9L2Ee2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Y7vAOdL2Ee2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Y7vAPNL2Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_P5USkNL4Ee2vSZc3OuTw8Q" name="Envio de dados para area financeira da empresa" outgoing="_SgePINMFEe2vSZc3OuTw8Q" incoming="_yT2hMNMFEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_P5USktL4Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_P5USkdL4Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_P5USk9L4Ee2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_P5USlNL4Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_P5USldL4Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_P5USltL4Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_P5USmNL4Ee2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_P5USl9L4Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_rANb0NMCEe2vSZc3OuTw8Q" name="As informações são o suficiente ?" outgoing="_rATicNMCEe2vSZc3OuTw8Q _veNRINMCEe2vSZc3OuTw8Q" incoming="_ckBVgNL2Ee2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rANb0tMCEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rANb0dMCEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rANb09MCEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4r9IMNMEEe2vSZc3OuTw8Q" name="Estimar os custos e receitas do projeto" outgoing="_9gaDwNMGEe2vSZc3OuTw8Q" incoming="_4r_kcNMEEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4r9IMtMEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4r9IMdMEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4r9IM9MEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4r9INNMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4r9INdMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4r9INtMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4r9IONMEEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4r9IN9MEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_8wsI8NMEEe2vSZc3OuTw8Q" name="Avaliar rentabilidade do projeto" outgoing="_9xwScNMGEe2vSZc3OuTw8Q" incoming="_8wvMQNMEEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8wswAdMEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8wswANMEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8wswAtMEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8wswA9MEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8wswBNMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8wswBdMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8wswB9MEEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8wswBtMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AriN4NMFEe2vSZc3OuTw8Q" name="Identificar fontes de financiamento" outgoing="_-GZswNMGEe2vSZc3OuTw8Q" incoming="_ArkqINMFEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AriN4tMFEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AriN4dMFEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AriN49MFEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AriN5NMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AriN5dMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_AriN5tMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_AriN6NMFEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_AriN59MFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_OaqQUNMFEe2vSZc3OuTw8Q" name="Receber dados e criar detalhadamente um relatorio " outgoing="_4r_kcNMEEe2vSZc3OuTw8Q _8wvMQNMEEe2vSZc3OuTw8Q _ArkqINMFEe2vSZc3OuTw8Q" incoming="_SgePINMFEe2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WS7CgtMEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WS7CgdMEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WS7Cg9MEEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WS7ChNMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WS7ChdMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WS7ChtMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WS7CiNMEEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WS7Ch9MEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryMessageEvent" xmi:id="_QBZkoNMFEe2vSZc3OuTw8Q" name="Dados Recebidos"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_OaqQWtMFEe2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_OaqQW9MFEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_OaqQWdMFEe2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_OaqQXNMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_gtqGkNMFEe2vSZc3OuTw8Q" name="Envio de dados para area de ánalise de riscos" outgoing="_FQGIwNMGEe2vSZc3OuTw8Q" incoming="_0HxV4NMFEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gtqGktMFEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gtqGkdMFEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gtqGk9MFEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gtqGlNMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gtqGldMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gtqGltMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gtqGmNMFEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gtqGl9MFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_A5n3wNMGEe2vSZc3OuTw8Q" name="Receber dados e criar detalhadamente um relatorio" outgoing="_I02o8NMGEe2vSZc3OuTw8Q _LszGcNMGEe2vSZc3OuTw8Q _SLuRsNMGEe2vSZc3OuTw8Q" incoming="_FQGIwNMGEe2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A5n3wtMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A5n3wdMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A5n3w9MGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_A5n3xNMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_A5n3xdMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_A5n3xtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_A5n3yNMGEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_A5n3x9MGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryMessageEvent" xmi:id="_F1gi8NMGEe2vSZc3OuTw8Q" name="Dados Recebidos"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_A5n3ytMGEe2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_A5n3y9MGEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_A5n3ydMGEe2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_A5n3zNMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_I00MsNMGEe2vSZc3OuTw8Q" name="Indentificar os riscos envolvidos no projeto" outgoing="_-8BtMNMGEe2vSZc3OuTw8Q" incoming="_I02o8NMGEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_I00MstMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_I00MsdMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_I00Ms9MGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_I00MtNMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_I00MtdMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_I00MttMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_I00MuNMGEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_I00Mt9MGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_LswqMNMGEe2vSZc3OuTw8Q" name="Avaliar a probabilidade e impacto dos riscos indentificados" outgoing="_-rYpINMGEe2vSZc3OuTw8Q" incoming="_LszGcNMGEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LswqMtMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LswqMdMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LswqM9MGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LswqNNMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LswqNdMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LswqNtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LswqONMGEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_LswqN9MGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SLr1cNMGEe2vSZc3OuTw8Q" name="Identificar estratégias para mitigar os riscos" outgoing="_-X2CENMGEe2vSZc3OuTw8Q" incoming="_SLuRsNMGEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SLscgdMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SLscgNMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SLscgtMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SLscg9MGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SLschNMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SLschdMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SLsch9MGEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SLschtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_6kK8INMGEe2vSZc3OuTw8Q" name="Enviar projeto para análise da gerencia" outgoing="_cFCDsNMHEe2vSZc3OuTw8Q" incoming="_9gaDwNMGEe2vSZc3OuTw8Q _9xwScNMGEe2vSZc3OuTw8Q _-GZswNMGEe2vSZc3OuTw8Q _-X2CENMGEe2vSZc3OuTw8Q _-rYpINMGEe2vSZc3OuTw8Q _-8BtMNMGEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6kLjMdMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6kLjMNMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6kLjMtMGEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6kLjM9MGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6kLjNNMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6kLjNdMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6kLjN9MGEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6kLjNtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ThANINMHEe2vSZc3OuTw8Q" name="Empresa/Gerencia">
        <elements xmi:type="process:ReceiveTask" xmi:id="_ZugRMNMHEe2vSZc3OuTw8Q" name="Análise do resultado do projeto" outgoing="_i1pb4NMHEe2vSZc3OuTw8Q" incoming="_cFCDsNMHEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zug4QdMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zug4QNMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zug4QtMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zug4Q9MHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zug4RNMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zug4RdMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zug4R9MHEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zug4RtMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_i1nmsNMHEe2vSZc3OuTw8Q" name="O Projeto é viavel para ser desenvolvido ?" outgoing="_upDYgNMHEe2vSZc3OuTw8Q _xqskkNMHEe2vSZc3OuTw8Q __916ENMHEe2vSZc3OuTw8Q" incoming="_i1pb4NMHEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_i1nmstMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_i1nmsdMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_i1nms9MHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_r3LGwNMHEe2vSZc3OuTw8Q" name="Enviar Projeto base para o cliente" outgoing="_Me7cENMIEe2vSZc3OuTw8Q" incoming="_upDYgNMHEe2vSZc3OuTw8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r3Lt0dMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r3Lt0NMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r3Lt0tMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_r3Lt09MHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_r3Lt1NMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r3Lt1dMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_r3Lt19MHEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_r3Lt1tMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_7hoNcNMHEe2vSZc3OuTw8Q" name="Planejar Proximas etapas para o projeto" incoming="__916ENMHEe2vSZc3OuTw8Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7ho0gdMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7ho0gNMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7ho0gtMHEe2vSZc3OuTw8Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7ho0g9MHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7ho0hNMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7ho0hdMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7ho0h9MHEe2vSZc3OuTw8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7ho0htMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_7ho0idMHEe2vSZc3OuTw8Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_7ho0itMHEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_7ho0iNMHEe2vSZc3OuTw8Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_7ho0i9MHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_PJiqRNLyEe2vSZc3OuTw8Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_PJiqRdLyEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_PJiqRtLyEe2vSZc3OuTw8Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_PJiqR9LyEe2vSZc3OuTw8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PJiqSNLyEe2vSZc3OuTw8Q" target="_5xZygNLyEe2vSZc3OuTw8Q" source="_PJiqM9LyEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PJiqSdLyEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_PJiqStLyEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DErUsNLzEe2vSZc3OuTw8Q" target="_-CgbUNLyEe2vSZc3OuTw8Q" source="_5xZygNLyEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DEr7wNLzEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_DEr7wdLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VONs8NLzEe2vSZc3OuTw8Q" target="_IDBeANLzEe2vSZc3OuTw8Q" source="_-CgbUNLyEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VONs8dLzEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_VONs8tLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yLYm4NLzEe2vSZc3OuTw8Q" target="_rNGmINLzEe2vSZc3OuTw8Q" source="_IDBeANLzEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yLYm4dLzEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_yLYm4tLzEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RYmQ0NL0Ee2vSZc3OuTw8Q" target="_Khq1QNL0Ee2vSZc3OuTw8Q" source="_rNGmINLzEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RYmQ0dL0Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_RYmQ0tL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S2XPUNL0Ee2vSZc3OuTw8Q" name="Não" target="_NlOF0NL0Ee2vSZc3OuTw8Q" source="_Khq1QNL0Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S2XPUdL0Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_S2XPUtL0Ee2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TZkqENL0Ee2vSZc3OuTw8Q" name="Sim" target="__ecYYNLzEe2vSZc3OuTw8Q" source="_Khq1QNL0Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TZkqEdL0Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_TZkqEtL0Ee2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0TiwwNL0Ee2vSZc3OuTw8Q" target="_rd9QINL0Ee2vSZc3OuTw8Q" source="_daCCYNL0Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0TiwwdL0Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_0TiwwtL0Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cXFiMNL1Ee2vSZc3OuTw8Q" target="_daCCYNL0Ee2vSZc3OuTw8Q" source="_W5R1sNL1Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cXFiMdL1Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_cXFiMtL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fWkyINL1Ee2vSZc3OuTw8Q" target="_L9VskNL1Ee2vSZc3OuTw8Q" source="_rd9QINL0Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fWkyIdL1Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_fWkyItL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wm31QNL1Ee2vSZc3OuTw8Q" target="_rYSQgNL1Ee2vSZc3OuTw8Q" source="_L9VskNL1Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wm4cUNL1Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_wm4cUdL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_755osNL1Ee2vSZc3OuTw8Q" target="_zqYCgNL1Ee2vSZc3OuTw8Q" source="_rYSQgNL1Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_755osdL1Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_755ostL1Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ckBVgNL2Ee2vSZc3OuTw8Q" target="_rANb0NMCEe2vSZc3OuTw8Q" source="_zqYCgNL1Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ckBVgdL2Ee2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_ckBVgtL2Ee2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rATicNMCEe2vSZc3OuTw8Q" name="Sim" target="_Y7vAMNL2Ee2vSZc3OuTw8Q" source="_rANb0NMCEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rATicdMCEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_rATictMCEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_veNRINMCEe2vSZc3OuTw8Q" name="Não" target="_daCCYNL0Ee2vSZc3OuTw8Q" source="_rANb0NMCEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_veNRIdMCEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_veNRItMCEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MY77ENMDEe2vSZc3OuTw8Q" target="_W5R1sNL1Ee2vSZc3OuTw8Q" source="__ecYYNLzEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MY77EdMDEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_MY8iINMDEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4r_kcNMEEe2vSZc3OuTw8Q" target="_4r9IMNMEEe2vSZc3OuTw8Q" source="_OaqQUNMFEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4r_kcdMEEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_4r_kctMEEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8wvMQNMEEe2vSZc3OuTw8Q" target="_8wsI8NMEEe2vSZc3OuTw8Q" source="_OaqQUNMFEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8wvMQdMEEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_8wvMQtMEEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ArkqINMFEe2vSZc3OuTw8Q" target="_AriN4NMFEe2vSZc3OuTw8Q" source="_OaqQUNMFEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ArkqIdMFEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_ArkqItMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SgePINMFEe2vSZc3OuTw8Q" target="_OaqQUNMFEe2vSZc3OuTw8Q" source="_P5USkNL4Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SgePIdMFEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SgePItMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yT2hMNMFEe2vSZc3OuTw8Q" target="_P5USkNL4Ee2vSZc3OuTw8Q" source="_Y7vAMNL2Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yT2hMdMFEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_yT2hMtMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0HxV4NMFEe2vSZc3OuTw8Q" target="_gtqGkNMFEe2vSZc3OuTw8Q" source="_Y7vAMNL2Ee2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0HxV4dMFEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_0HxV4tMFEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FQGIwNMGEe2vSZc3OuTw8Q" target="_A5n3wNMGEe2vSZc3OuTw8Q" source="_gtqGkNMFEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FQGIwdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_FQGIwtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_I02o8NMGEe2vSZc3OuTw8Q" target="_I00MsNMGEe2vSZc3OuTw8Q" source="_A5n3wNMGEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_I02o8dMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_I02o8tMGEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LszGcNMGEe2vSZc3OuTw8Q" target="_LswqMNMGEe2vSZc3OuTw8Q" source="_A5n3wNMGEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LszGcdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_LszGctMGEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SLuRsNMGEe2vSZc3OuTw8Q" target="_SLr1cNMGEe2vSZc3OuTw8Q" source="_A5n3wNMGEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SLu4wNMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SLu4wdMGEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9gaDwNMGEe2vSZc3OuTw8Q" target="_6kK8INMGEe2vSZc3OuTw8Q" source="_4r9IMNMEEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9gaDwdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_9gaDwtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9xwScNMGEe2vSZc3OuTw8Q" target="_6kK8INMGEe2vSZc3OuTw8Q" source="_8wsI8NMEEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9xwScdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_9xwSctMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-GZswNMGEe2vSZc3OuTw8Q" target="_6kK8INMGEe2vSZc3OuTw8Q" source="_AriN4NMFEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-GZswdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_-GZswtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-X2CENMGEe2vSZc3OuTw8Q" target="_6kK8INMGEe2vSZc3OuTw8Q" source="_SLr1cNMGEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-X2CEdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_-X2CEtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-rYpINMGEe2vSZc3OuTw8Q" target="_6kK8INMGEe2vSZc3OuTw8Q" source="_LswqMNMGEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-rYpIdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_-rYpItMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-8BtMNMGEe2vSZc3OuTw8Q" target="_6kK8INMGEe2vSZc3OuTw8Q" source="_I00MsNMGEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-8BtMdMGEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_-8BtMtMGEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cFCDsNMHEe2vSZc3OuTw8Q" target="_ZugRMNMHEe2vSZc3OuTw8Q" source="_6kK8INMGEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cFCDsdMHEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_cFCDstMHEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i1pb4NMHEe2vSZc3OuTw8Q" target="_i1nmsNMHEe2vSZc3OuTw8Q" source="_ZugRMNMHEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i1pb4dMHEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_i1pb4tMHEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_upDYgNMHEe2vSZc3OuTw8Q" name="Sim" target="_r3LGwNMHEe2vSZc3OuTw8Q" source="_i1nmsNMHEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_upDYgdMHEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_upD_kNMHEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xqskkNMHEe2vSZc3OuTw8Q" name="Não" target="_Y7vAMNL2Ee2vSZc3OuTw8Q" source="_i1nmsNMHEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xqskkdMHEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_xqskktMHEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__916ENMHEe2vSZc3OuTw8Q" target="_7hoNcNMHEe2vSZc3OuTw8Q" source="_i1nmsNMHEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__916EdMHEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="__916EtMHEe2vSZc3OuTw8Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Me7cENMIEe2vSZc3OuTw8Q" target="_KDtW0NMIEe2vSZc3OuTw8Q" source="_r3LGwNMHEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Me7cEdMIEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Me7cEtMIEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_P3nPINMIEe2vSZc3OuTw8Q" target="_OyzjMNMIEe2vSZc3OuTw8Q" source="_KDtW0NMIEe2vSZc3OuTw8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_P3nPIdMIEe2vSZc3OuTw8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_P3nPItMIEe2vSZc3OuTw8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_PJiqS9LyEe2vSZc3OuTw8Q" documentation="Este é um exemplo de ator que é mapeado para qualquer usuário ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_PJiqTNLyEe2vSZc3OuTw8Q"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PJiqTdLyEe2vSZc3OuTw8Q">
        <name xmi:type="expression:Expression" xmi:id="_PJiqTtLyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PJiqT9LyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PJiqUNLyEe2vSZc3OuTw8Q">
        <name xmi:type="expression:Expression" xmi:id="_PJiqUdLyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PJiqUtLyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PJiqU9LyEe2vSZc3OuTw8Q">
        <name xmi:type="expression:Expression" xmi:id="_PJiqVNLyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PJiqVdLyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PJiqVtLyEe2vSZc3OuTw8Q">
        <name xmi:type="expression:Expression" xmi:id="_PJiqV9LyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PJiqWNLyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PJiqWdLyEe2vSZc3OuTw8Q">
        <name xmi:type="expression:Expression" xmi:id="_PJiqWtLyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PJiqW9LyEe2vSZc3OuTw8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_PJiqXNLyEe2vSZc3OuTw8Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_PJiqXdLyEe2vSZc3OuTw8Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_PJiqXtLyEe2vSZc3OuTw8Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_PJiqX9LyEe2vSZc3OuTw8Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_PJiqYNLyEe2vSZc3OuTw8Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_PJiqYdLyEe2vSZc3OuTw8Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_PJiqYtLyEe2vSZc3OuTw8Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_PJiqY9LyEe2vSZc3OuTw8Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_PJiqZNLyEe2vSZc3OuTw8Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_PJiqZdLyEe2vSZc3OuTw8Q" type="Process" element="_PJiqMNLyEe2vSZc3OuTw8Q" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_PJiqZtLyEe2vSZc3OuTw8Q" type="2007" element="_PJiqMdLyEe2vSZc3OuTw8Q">
      <children xmi:type="notation:DecorationNode" xmi:id="_PJiqZ9LyEe2vSZc3OuTw8Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_PJiqaNLyEe2vSZc3OuTw8Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_PJiqadLyEe2vSZc3OuTw8Q" type="3007" element="_PJiqMtLyEe2vSZc3OuTw8Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_PJiqatLyEe2vSZc3OuTw8Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PJiqa9LyEe2vSZc3OuTw8Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PJiqb9LyEe2vSZc3OuTw8Q" type="3002" element="_PJiqM9LyEe2vSZc3OuTw8Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PJiqcNLyEe2vSZc3OuTw8Q" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PJiqcdLyEe2vSZc3OuTw8Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PJiqctLyEe2vSZc3OuTw8Q" x="48" y="17"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5xaZkNLyEe2vSZc3OuTw8Q" type="3005" element="_5xZygNLyEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5xaZktLyEe2vSZc3OuTw8Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5xaZkdLyEe2vSZc3OuTw8Q" x="48" y="84" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-ChCYNLyEe2vSZc3OuTw8Q" type="3025" element="_-CgbUNLyEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-ChCYtLyEe2vSZc3OuTw8Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-ChCYdLyEe2vSZc3OuTw8Q" x="42" y="217" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rd93MNL0Ee2vSZc3OuTw8Q" type="3026" element="_rd9QINL0Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rd93MtL0Ee2vSZc3OuTw8Q" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rd93MdL0Ee2vSZc3OuTw8Q" x="308" y="140" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L9WToNL1Ee2vSZc3OuTw8Q" type="3005" element="_L9VskNL1Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_L9WTotL1Ee2vSZc3OuTw8Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L9WTodL1Ee2vSZc3OuTw8Q" x="555" y="145" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rYS3mNL1Ee2vSZc3OuTw8Q" type="3025" element="_rYSQgNL1Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rYS3mtL1Ee2vSZc3OuTw8Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rYS3mdL1Ee2vSZc3OuTw8Q" x="555" y="274" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KDt94NMIEe2vSZc3OuTw8Q" type="3026" element="_KDtW0NMIEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KDt94tMIEe2vSZc3OuTw8Q" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KDt94dMIEe2vSZc3OuTw8Q" x="1809" y="255"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Oy0KQ9MIEe2vSZc3OuTw8Q" type="3003" element="_OyzjMNMIEe2vSZc3OuTw8Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Oy0KRdMIEe2vSZc3OuTw8Q" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Oy0KRtMIEe2vSZc3OuTw8Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Oy0KRNMIEe2vSZc3OuTw8Q" x="1844" y="140"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PJiqc9LyEe2vSZc3OuTw8Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PJiqdNLyEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PJiqddLyEe2vSZc3OuTw8Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PJiqdtLyEe2vSZc3OuTw8Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PJiqd9LyEe2vSZc3OuTw8Q" x="48" y="10" width="1297" height="394"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_gJztQNLyEe2vSZc3OuTw8Q" type="3007" element="_gJzGMNLyEe2vSZc3OuTw8Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_gJ0UUNLyEe2vSZc3OuTw8Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_gJ0UUdLyEe2vSZc3OuTw8Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_IDCsINLzEe2vSZc3OuTw8Q" type="3026" element="_IDBeANLzEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IDCsItLzEe2vSZc3OuTw8Q" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IDCsIdLzEe2vSZc3OuTw8Q" x="48" y="38" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rNH0QNLzEe2vSZc3OuTw8Q" type="3005" element="_rNGmINLzEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rNH0QtLzEe2vSZc3OuTw8Q" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_Hb5sQNL2Ee2vSZc3OuTw8Q" type="3043" element="_Hb5FMNL2Ee2vSZc3OuTw8Q" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_Hb5sQtL2Ee2vSZc3OuTw8Q" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Hb5sQ9L2Ee2vSZc3OuTw8Q" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Hb5sQdL2Ee2vSZc3OuTw8Q"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rNH0QdLzEe2vSZc3OuTw8Q" x="48" y="171" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__ecYbdLzEe2vSZc3OuTw8Q" type="3005" element="__ecYYNLzEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__ecYb9LzEe2vSZc3OuTw8Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__ecYbtLzEe2vSZc3OuTw8Q" x="358" y="304" width="141" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KhrcUNL0Ee2vSZc3OuTw8Q" type="3009" element="_Khq1QNL0Ee2vSZc3OuTw8Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_KhrcUtL0Ee2vSZc3OuTw8Q" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_KhrcU9L0Ee2vSZc3OuTw8Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KhrcUdL0Ee2vSZc3OuTw8Q" x="213" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NlPT8NL0Ee2vSZc3OuTw8Q" type="3003" element="_NlOF0NL0Ee2vSZc3OuTw8Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NlPT8tL0Ee2vSZc3OuTw8Q" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NlPT89L0Ee2vSZc3OuTw8Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NlPT8dL0Ee2vSZc3OuTw8Q" x="220" y="428"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_daCpcNL0Ee2vSZc3OuTw8Q" type="3025" element="_daCCYNL0Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_daCpctL0Ee2vSZc3OuTw8Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_daCpcdL0Ee2vSZc3OuTw8Q" x="349" y="35" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_W5ScwNL1Ee2vSZc3OuTw8Q" type="3005" element="_W5R1sNL1Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_W5ScwtL1Ee2vSZc3OuTw8Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_W5ScwdL1Ee2vSZc3OuTw8Q" x="349" y="171" width="158" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zqYpkNL1Ee2vSZc3OuTw8Q" type="3026" element="_zqYCgNL1Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zqYpktL1Ee2vSZc3OuTw8Q" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zqYpkdL1Ee2vSZc3OuTw8Q" x="631" y="36" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Y7vnQNL2Ee2vSZc3OuTw8Q" type="3005" element="_Y7vAMNL2Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Y7vnQtL2Ee2vSZc3OuTw8Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y7vnQdL2Ee2vSZc3OuTw8Q" x="628" y="314" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P5U5oNL4Ee2vSZc3OuTw8Q" type="3025" element="_P5USkNL4Ee2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_P5U5otL4Ee2vSZc3OuTw8Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P5U5odL4Ee2vSZc3OuTw8Q" x="821" y="428" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rAOC4NMCEe2vSZc3OuTw8Q" type="3009" element="_rANb0NMCEe2vSZc3OuTw8Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rAOC4tMCEe2vSZc3OuTw8Q" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rAOC49MCEe2vSZc3OuTw8Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rAOC4dMCEe2vSZc3OuTw8Q" x="666" y="165"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4r9vQNMEEe2vSZc3OuTw8Q" type="3027" element="_4r9IMNMEEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4r9vQtMEEe2vSZc3OuTw8Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4r9vQdMEEe2vSZc3OuTw8Q" x="1315" y="314" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8wswCNMEEe2vSZc3OuTw8Q" type="3027" element="_8wsI8NMEEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8wswCtMEEe2vSZc3OuTw8Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8wswCdMEEe2vSZc3OuTw8Q" x="1315" y="412" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ari08NMFEe2vSZc3OuTw8Q" type="3027" element="_AriN4NMFEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ari08tMFEe2vSZc3OuTw8Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ari08dMFEe2vSZc3OuTw8Q" x="1315" y="497" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OaqQXdMFEe2vSZc3OuTw8Q" type="3005" element="_OaqQUNMFEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OaqQX9MFEe2vSZc3OuTw8Q" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_QBaLsNMFEe2vSZc3OuTw8Q" type="3035" element="_QBZkoNMFEe2vSZc3OuTw8Q" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_QBaLstMFEe2vSZc3OuTw8Q" type="5054">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_QBaywNMFEe2vSZc3OuTw8Q" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QBaLsdMFEe2vSZc3OuTw8Q" x="19" y="61"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OaqQXtMFEe2vSZc3OuTw8Q" x="1049" y="428" width="175" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gtqtoNMFEe2vSZc3OuTw8Q" type="3025" element="_gtqGkNMFEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gtqtotMFEe2vSZc3OuTw8Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gtqtodMFEe2vSZc3OuTw8Q" x="821" y="184" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A5oe0NMGEe2vSZc3OuTw8Q" type="3005" element="_A5n3wNMGEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_A5oe0tMGEe2vSZc3OuTw8Q" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_F1hKANMGEe2vSZc3OuTw8Q" type="3035" element="_F1gi8NMGEe2vSZc3OuTw8Q" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_F1hKAtMGEe2vSZc3OuTw8Q" type="5054">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_F1hKA9MGEe2vSZc3OuTw8Q" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F1hKAdMGEe2vSZc3OuTw8Q"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A5oe0dMGEe2vSZc3OuTw8Q" x="992" y="127" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_I00zwNMGEe2vSZc3OuTw8Q" type="3027" element="_I00MsNMGEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_I00zwtMGEe2vSZc3OuTw8Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I00zwdMGEe2vSZc3OuTw8Q" x="1176" y="26" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LsxRQNMGEe2vSZc3OuTw8Q" type="3027" element="_LswqMNMGEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_LsxRQtMGEe2vSZc3OuTw8Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LsxRQdMGEe2vSZc3OuTw8Q" x="1176" y="127" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SLsciNMGEe2vSZc3OuTw8Q" type="3027" element="_SLr1cNMGEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SLscitMGEe2vSZc3OuTw8Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SLscidMGEe2vSZc3OuTw8Q" x="1176" y="229" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6kLjONMGEe2vSZc3OuTw8Q" type="3025" element="_6kK8INMGEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6kLjOtMGEe2vSZc3OuTw8Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6kLjOdMGEe2vSZc3OuTw8Q" x="1562" y="564" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_gJztQdLyEe2vSZc3OuTw8Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_gJztQtLyEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_gJztQ9LyEe2vSZc3OuTw8Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_gJ0UUtLyEe2vSZc3OuTw8Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gJztRNLyEe2vSZc3OuTw8Q" x="48" y="394" width="1914" height="695"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_ThA0MNMHEe2vSZc3OuTw8Q" type="3007" element="_ThANINMHEe2vSZc3OuTw8Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_ThBbQNMHEe2vSZc3OuTw8Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ThBbQdMHEe2vSZc3OuTw8Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Zug4SNMHEe2vSZc3OuTw8Q" type="3026" element="_ZugRMNMHEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Zug4StMHEe2vSZc3OuTw8Q" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zug4SdMHEe2vSZc3OuTw8Q" x="1572" y="25" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_i1oNwNMHEe2vSZc3OuTw8Q" type="3009" element="_i1nmsNMHEe2vSZc3OuTw8Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_i1oNwtMHEe2vSZc3OuTw8Q" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_i1oNw9MHEe2vSZc3OuTw8Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_i1oNwdMHEe2vSZc3OuTw8Q" x="1619" y="154"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r3Lt2NMHEe2vSZc3OuTw8Q" type="3025" element="_r3LGwNMHEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r3Lt2tMHEe2vSZc3OuTw8Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r3Lt2dMHEe2vSZc3OuTw8Q" x="1771" y="30" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7ho0jNMHEe2vSZc3OuTw8Q" type="3005" element="_7hoNcNMHEe2vSZc3OuTw8Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7hpbkNMHEe2vSZc3OuTw8Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7ho0jdMHEe2vSZc3OuTw8Q" x="1771" y="211" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ThA0MdMHEe2vSZc3OuTw8Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ThA0MtMHEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ThA0M9MHEe2vSZc3OuTw8Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ThBbQtMHEe2vSZc3OuTw8Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ThA0NNMHEe2vSZc3OuTw8Q" x="48" y="1089" width="1981" height="321"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_PJiqeNLyEe2vSZc3OuTw8Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_PJiqedLyEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_PJiqetLyEe2vSZc3OuTw8Q"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_PJiqe9LyEe2vSZc3OuTw8Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PJiqfNLyEe2vSZc3OuTw8Q" width="2062" height="281"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_PJiqfdLyEe2vSZc3OuTw8Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_PJiqftLyEe2vSZc3OuTw8Q" type="4001" element="_PJiqSNLyEe2vSZc3OuTw8Q" source="_PJiqb9LyEe2vSZc3OuTw8Q" target="_5xaZkNLyEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PJiqf9LyEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PJiqgNLyEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PJiqgdLyEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PJiqgtLyEe2vSZc3OuTw8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DEr7wtLzEe2vSZc3OuTw8Q" type="4001" element="_DErUsNLzEe2vSZc3OuTw8Q" source="_5xaZkNLyEe2vSZc3OuTw8Q" target="_-ChCYNLyEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DEsi0NLzEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DEsi0dLzEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DEr7w9LzEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DEr7xNLzEe2vSZc3OuTw8Q" points="[0, 1, 10, -79]$[0, 74, 10, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DEtw8NLzEe2vSZc3OuTw8Q" id="(0.49166666666666664,0.9833333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DEtw8dLzEe2vSZc3OuTw8Q" id="(0.49,0.12)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VOOUANLzEe2vSZc3OuTw8Q" type="4001" element="_VONs8NLzEe2vSZc3OuTw8Q" source="_-ChCYNLyEe2vSZc3OuTw8Q" target="_IDCsINLzEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VOOUA9LzEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VOOUBNLzEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VOOUAdLzEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VOOUAtLzEe2vSZc3OuTw8Q" points="[-44, 33, -1, -118]$[-44, 144, -1, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VOPiINLzEe2vSZc3OuTw8Q" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VOPiIdLzEe2vSZc3OuTw8Q" id="(0.4666666666666667,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yLZN8NLzEe2vSZc3OuTw8Q" type="4001" element="_yLYm4NLzEe2vSZc3OuTw8Q" source="_IDCsINLzEe2vSZc3OuTw8Q" target="_rNH0QNLzEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yLZN89LzEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yLZN9NLzEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yLZN8dLzEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yLZN8tLzEe2vSZc3OuTw8Q" points="[-79, 48, 5, -63]$[-79, 104, 5, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yLacENLzEe2vSZc3OuTw8Q" id="(1.0,0.37662337662337664)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yLacEdLzEe2vSZc3OuTw8Q" id="(0.4666666666666667,0.11666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RYm34NL0Ee2vSZc3OuTw8Q" type="4001" element="_RYmQ0NL0Ee2vSZc3OuTw8Q" source="_rNH0QNLzEe2vSZc3OuTw8Q" target="_KhrcUNL0Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RYm349L0Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RYm35NL0Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RYm34dL0Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RYm34tL0Ee2vSZc3OuTw8Q" points="[0, 30, -34, -59]$[34, 30, 0, -59]$[34, 87, 0, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RYne8NL0Ee2vSZc3OuTw8Q" id="(1.0,0.35526315789473684)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RYne8dL0Ee2vSZc3OuTw8Q" id="(0.4883720930232558,0.046511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S2XPU9L0Ee2vSZc3OuTw8Q" type="4001" element="_S2XPUNL0Ee2vSZc3OuTw8Q" source="_KhrcUNL0Ee2vSZc3OuTw8Q" target="_NlPT8NL0Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S2X2YNL0Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S2X2YdL0Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S2XPVNL0Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S2XPVdL0Ee2vSZc3OuTw8Q" points="[-23, 14, 6, -84]$[-35, 95, -6, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S2YdcNL0Ee2vSZc3OuTw8Q" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S2YdcdL0Ee2vSZc3OuTw8Q" id="(0.23333333333333334,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TZlRINL0Ee2vSZc3OuTw8Q" type="4001" element="_TZkqENL0Ee2vSZc3OuTw8Q" source="_KhrcUNL0Ee2vSZc3OuTw8Q" target="__ecYbdLzEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TZlRI9L0Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TZlRJNL0Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TZlRIdL0Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TZlRItL0Ee2vSZc3OuTw8Q" points="[-9, -16, -94, 60]$[85, -69, 0, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TZmfQNL0Ee2vSZc3OuTw8Q" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TZmfQdL0Ee2vSZc3OuTw8Q" id="(0.5035460992907801,0.9)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0TjX0NL0Ee2vSZc3OuTw8Q" type="4001" element="_0TiwwNL0Ee2vSZc3OuTw8Q" source="_daCpcNL0Ee2vSZc3OuTw8Q" target="_rd93MNL0Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0TjX09L0Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0TjX1NL0Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0TjX0dL0Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0TjX0tL0Ee2vSZc3OuTw8Q" points="[-123, -30, 3, 181]$[-123, -205, 3, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0Tkl8NL0Ee2vSZc3OuTw8Q" id="(1.0,0.375)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0Tkl8dL0Ee2vSZc3OuTw8Q" id="(0.5357142857142857,0.9142857142857143)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cXGJQNL1Ee2vSZc3OuTw8Q" type="4001" element="_cXFiMNL1Ee2vSZc3OuTw8Q" source="_W5ScwNL1Ee2vSZc3OuTw8Q" target="_daCpcNL0Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cXGJQ9L1Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cXGJRNL1Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cXGJQdL1Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cXGJQtL1Ee2vSZc3OuTw8Q" points="[-66, -30, 7, 66]$[-66, -86, 7, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cXGwUNL1Ee2vSZc3OuTw8Q" id="(1.0,0.379746835443038)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cXGwUdL1Ee2vSZc3OuTw8Q" id="(0.53125,0.875)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fWkyI9L1Ee2vSZc3OuTw8Q" type="4001" element="_fWkyINL1Ee2vSZc3OuTw8Q" source="_rd93MNL0Ee2vSZc3OuTw8Q" target="_L9WToNL1Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fWkyJtL1Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fWkyJ9L1Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fWkyJNL1Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fWkyJdL1Ee2vSZc3OuTw8Q" points="[0, -1, -80, 0]$[78, -1, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fWmAQNL1Ee2vSZc3OuTw8Q" id="(1.0,0.4)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fWmAQdL1Ee2vSZc3OuTw8Q" id="(0.02,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wm4cUtL1Ee2vSZc3OuTw8Q" type="4001" element="_wm31QNL1Ee2vSZc3OuTw8Q" source="_L9WToNL1Ee2vSZc3OuTw8Q" target="_rYS3mNL1Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wm4cVdL1Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wm4cVtL1Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wm4cU9L1Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wm4cVNL1Ee2vSZc3OuTw8Q" points="[-44, 32, 16, -72]$[-44, 101, 16, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wm5qcNL1Ee2vSZc3OuTw8Q" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wm5qcdL1Ee2vSZc3OuTw8Q" id="(0.5,0.05)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_755os9L1Ee2vSZc3OuTw8Q" type="4001" element="_755osNL1Ee2vSZc3OuTw8Q" source="_rYS3mNL1Ee2vSZc3OuTw8Q" target="_zqYpkNL1Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_755ottL1Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_755ot9L1Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_755otNL1Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_755otdL1Ee2vSZc3OuTw8Q" points="[-61, 33, -2, -116]$[-61, 144, -2, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_75620NL1Ee2vSZc3OuTw8Q" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_75620dL1Ee2vSZc3OuTw8Q" id="(0.51,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ckBVg9L2Ee2vSZc3OuTw8Q" type="4001" element="_ckBVgNL2Ee2vSZc3OuTw8Q" source="_zqYpkNL1Ee2vSZc3OuTw8Q" target="_rAOC4NMCEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ckB8kNL2Ee2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ckB8kdL2Ee2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ckBVhNL2Ee2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ckBVhdL2Ee2vSZc3OuTw8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ckCjoNL2Ee2vSZc3OuTw8Q" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rATic9MCEe2vSZc3OuTw8Q" type="4001" element="_rATicNMCEe2vSZc3OuTw8Q" source="_rAOC4NMCEe2vSZc3OuTw8Q" target="_Y7vnQNL2Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rAUJgNMCEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rAUJgdMCEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rATidNMCEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rATiddMCEe2vSZc3OuTw8Q" points="[0, 22, 38, -131]$[0, 123, 38, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_veNRI9MCEe2vSZc3OuTw8Q" type="4001" element="_veNRINMCEe2vSZc3OuTw8Q" source="_rAOC4NMCEe2vSZc3OuTw8Q" target="_daCpcNL0Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_veN4MtMCEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_veN4M9MCEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_veN4MNMCEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_veN4MdMCEe2vSZc3OuTw8Q" points="[-34, -15, 175, 72]$[-200, -84, 9, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_veOfQNMCEe2vSZc3OuTw8Q" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_veOfQdMCEe2vSZc3OuTw8Q" id="(0.94375,0.8625)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MY8iIdMDEe2vSZc3OuTw8Q" type="4001" element="_MY77ENMDEe2vSZc3OuTw8Q" source="__ecYbdLzEe2vSZc3OuTw8Q" target="_W5ScwNL1Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MY8iJNMDEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MY8iJdMDEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MY8iItMDEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MY8iI9MDEe2vSZc3OuTw8Q" points="[-72, -27, 8, 64]$[-72, -81, 8, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MY9JMNMDEe2vSZc3OuTw8Q" id="(1.0,0.38571428571428573)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MY9JMdMDEe2vSZc3OuTw8Q" id="(0.4430379746835443,0.8734177215189873)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4r_kc9MEEe2vSZc3OuTw8Q" type="4001" element="_4r_kcNMEEe2vSZc3OuTw8Q" source="_OaqQXdMFEe2vSZc3OuTw8Q" target="_4r9vQNMEEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4sALgNMEEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4sALgdMEEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4r_kdNMEEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4r_kddMEEe2vSZc3OuTw8Q" points="[0, -34, -257, 84]$[0, -107, -257, 11]$[197, -107, -60, 11]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8wvMQ9MEEe2vSZc3OuTw8Q" type="4001" element="_8wvMQNMEEe2vSZc3OuTw8Q" source="_OaqQXdMFEe2vSZc3OuTw8Q" target="_8wswCNMEEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8wvMRtMEEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8wvMR9MEEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8wvMRNMEEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8wvMRdMEEe2vSZc3OuTw8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ArkqI9MFEe2vSZc3OuTw8Q" type="4001" element="_ArkqINMFEe2vSZc3OuTw8Q" source="_OaqQXdMFEe2vSZc3OuTw8Q" target="_Ari08NMFEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ArkqJtMFEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ArkqJ9MFEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ArkqJNMFEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ArkqJdMFEe2vSZc3OuTw8Q" points="[0, 35, -257, -30]$[0, 64, -257, -1]$[197, 64, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SgePI9MFEe2vSZc3OuTw8Q" type="4001" element="_SgePINMFEe2vSZc3OuTw8Q" source="_P5U5oNL4Ee2vSZc3OuTw8Q" target="_OaqQXdMFEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SgePJtMFEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sge2MNMFEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SgePJNMFEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SgePJdMFEe2vSZc3OuTw8Q" points="[0, 8, -87, 0]$[75, 7, -12, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SgfdQNMFEe2vSZc3OuTw8Q" id="(1.0,0.38571428571428573)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SgfdQdMFEe2vSZc3OuTw8Q" id="(0.08633093525179857,0.4927536231884058)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yT2hM9MFEe2vSZc3OuTw8Q" type="4001" element="_yT2hMNMFEe2vSZc3OuTw8Q" source="_Y7vnQNL2Ee2vSZc3OuTw8Q" target="_P5U5oNL4Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yT3IQNMFEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yT3IQdMFEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yT2hNNMFEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yT2hNdMFEe2vSZc3OuTw8Q" points="[-60, 31, -134, -90]$[-60, 119, -134, -2]$[73, 119, -1, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yT3vUNMFEe2vSZc3OuTw8Q" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yT3vUdMFEe2vSZc3OuTw8Q" id="(0.007142857142857143,0.5142857142857142)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0HxV49MFEe2vSZc3OuTw8Q" type="4001" element="_0HxV4NMFEe2vSZc3OuTw8Q" source="_Y7vnQNL2Ee2vSZc3OuTw8Q" target="_gtqtoNMFEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0HxV5tMFEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0HxV59MFEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0HxV5NMFEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0HxV5dMFEe2vSZc3OuTw8Q" points="[0, 0, -79, 129]$[73, -130, -6, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0HykANMFEe2vSZc3OuTw8Q" id="(1.0,0.5166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0HykAdMFEe2vSZc3OuTw8Q" id="(0.04285714285714286,0.45714285714285713)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FQGIw9MGEe2vSZc3OuTw8Q" type="4001" element="_FQGIwNMGEe2vSZc3OuTw8Q" source="_gtqtoNMFEe2vSZc3OuTw8Q" target="_A5oe0NMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FQGv0NMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FQGv0dMGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FQGIxNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FQGIxdMGEe2vSZc3OuTw8Q" points="[0, -3, -92, 0]$[88, -3, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FQHW4NMGEe2vSZc3OuTw8Q" id="(1.0,0.37142857142857144)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FQHW4dMGEe2vSZc3OuTw8Q" id="(0.02857142857142857,0.5142857142857142)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_I02o89MGEe2vSZc3OuTw8Q" type="4001" element="_I02o8NMGEe2vSZc3OuTw8Q" source="_A5oe0NMGEe2vSZc3OuTw8Q" target="_I00zwNMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_I03QANMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_I03QAdMGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_I02o9NMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_I02o9dMGEe2vSZc3OuTw8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LszGc9MGEe2vSZc3OuTw8Q" type="4001" element="_LszGcNMGEe2vSZc3OuTw8Q" source="_A5oe0NMGEe2vSZc3OuTw8Q" target="_LsxRQNMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LszGdtMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LszGd9MGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LszGdNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LszGddMGEe2vSZc3OuTw8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SLu4wtMGEe2vSZc3OuTw8Q" type="4001" element="_SLuRsNMGEe2vSZc3OuTw8Q" source="_A5oe0NMGEe2vSZc3OuTw8Q" target="_SLsciNMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SLu4xdMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SLu4xtMGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SLu4w9MGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SLu4xNMGEe2vSZc3OuTw8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9gaDw9MGEe2vSZc3OuTw8Q" type="4001" element="_9gaDwNMGEe2vSZc3OuTw8Q" source="_4r9vQNMEEe2vSZc3OuTw8Q" target="_6kLjONMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9gaDxtMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9gaDx9MGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9gaDxNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9gaDxdMGEe2vSZc3OuTw8Q" points="[0, 0, -121, 65]$[108, -65, -13, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9gaq0NMGEe2vSZc3OuTw8Q" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9gaq0dMGEe2vSZc3OuTw8Q" id="(0.10833333333333334,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9xwSc9MGEe2vSZc3OuTw8Q" type="4001" element="_9xwScNMGEe2vSZc3OuTw8Q" source="_8wswCNMEEe2vSZc3OuTw8Q" target="_6kLjONMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9xwSdtMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9xwSd9MGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9xwSdNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9xwSddMGEe2vSZc3OuTw8Q" points="[0, 0, -168, 167]$[108, -159, -60, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9xw5gNMGEe2vSZc3OuTw8Q" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-GZsw9MGEe2vSZc3OuTw8Q" type="4001" element="_-GZswNMGEe2vSZc3OuTw8Q" source="_Ari08NMFEe2vSZc3OuTw8Q" target="_6kLjONMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-GZsxtMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-GZsx9MGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-GZsxNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-GZsxdMGEe2vSZc3OuTw8Q" points="[0, 0, -183, 232]$[190, -222, 7, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-Ga64NMGEe2vSZc3OuTw8Q" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-Ga64dMGEe2vSZc3OuTw8Q" id="(0.625,0.8333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-X2CE9MGEe2vSZc3OuTw8Q" type="4001" element="_-X2CENMGEe2vSZc3OuTw8Q" source="_SLsciNMGEe2vSZc3OuTw8Q" target="_6kLjONMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-X2CFtMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-X2CF9MGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-X2CFNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-X2CFdMGEe2vSZc3OuTw8Q" points="[0, 4, -247, 0]$[227, -1, -20, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-X2pINMGEe2vSZc3OuTw8Q" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-X3QMNMGEe2vSZc3OuTw8Q" id="(0.16666666666666666,0.3333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-rYpI9MGEe2vSZc3OuTw8Q" type="4001" element="_-rYpINMGEe2vSZc3OuTw8Q" source="_LsxRQNMGEe2vSZc3OuTw8Q" target="_6kLjONMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-rYpJtMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-rYpJ9MGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-rYpJNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-rYpJdMGEe2vSZc3OuTw8Q" points="[0, 0, -287, -115]$[227, 115, -60, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-rZQMNMGEe2vSZc3OuTw8Q" id="(1.0,0.44285714285714284)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-8BtM9MGEe2vSZc3OuTw8Q" type="4001" element="_-8BtMNMGEe2vSZc3OuTw8Q" source="_I00zwNMGEe2vSZc3OuTw8Q" target="_6kLjONMGEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-8BtNtMGEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-8BtN9MGEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-8BtNNMGEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-8BtNdMGEe2vSZc3OuTw8Q" points="[0, 0, -289, -197]$[290, 187, 1, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-8C7UNMGEe2vSZc3OuTw8Q" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-8C7UdMGEe2vSZc3OuTw8Q" id="(0.5166666666666667,0.16666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cFCDs9MHEe2vSZc3OuTw8Q" type="4001" element="_cFCDsNMHEe2vSZc3OuTw8Q" source="_6kLjONMGEe2vSZc3OuTw8Q" target="_Zug4SNMHEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cFCDttMHEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cFCDt9MHEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cFCDtNMHEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cFCDtdMHEe2vSZc3OuTw8Q" points="[-7, 31, 22, -107]$[-27, 127, 2, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cFDR0NMHEe2vSZc3OuTw8Q" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cFDR0dMHEe2vSZc3OuTw8Q" id="(0.53,0.22)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_i1pb49MHEe2vSZc3OuTw8Q" type="4001" element="_i1pb4NMHEe2vSZc3OuTw8Q" source="_Zug4SNMHEe2vSZc3OuTw8Q" target="_i1oNwNMHEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i1pb5tMHEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i1qC8NMHEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i1pb5NMHEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i1pb5dMHEe2vSZc3OuTw8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_upD_kdMHEe2vSZc3OuTw8Q" type="4001" element="_upDYgNMHEe2vSZc3OuTw8Q" source="_i1oNwNMHEe2vSZc3OuTw8Q" target="_r3Lt2NMHEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_upD_lNMHEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_upD_ldMHEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_upD_ktMHEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_upD_k9MHEe2vSZc3OuTw8Q" points="[-14, 7, -181, 101]$[166, -91, -1, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_upEmoNMHEe2vSZc3OuTw8Q" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_upEmodMHEe2vSZc3OuTw8Q" id="(0.48333333333333334,0.95)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xqtLoNMHEe2vSZc3OuTw8Q" type="4001" element="_xqskkNMHEe2vSZc3OuTw8Q" source="_i1oNwNMHEe2vSZc3OuTw8Q" target="_Y7vnQNL2Ee2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xqtLo9MHEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xqtLpNMHEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xqtLodMHEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xqtLotMHEe2vSZc3OuTw8Q" points="[-22, -27, 956, 479]$[-100, -27, 878, 479]$[-100, -217, 878, 289]$[-971, -217, 7, 289]$[-971, -502, 7, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xqtysNMHEe2vSZc3OuTw8Q" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__916E9MHEe2vSZc3OuTw8Q" type="4001" element="__916ENMHEe2vSZc3OuTw8Q" source="_i1oNwNMHEe2vSZc3OuTw8Q" target="_7ho0jNMHEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__92hINMHEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__92hIdMHEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__916FNMHEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__916FdMHEe2vSZc3OuTw8Q" points="[0, -7, -152, -65]$[70, -7, -82, -65]$[70, 56, -82, -2]$[147, 56, -5, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__93IMNMHEe2vSZc3OuTw8Q" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__93IMdMHEe2vSZc3OuTw8Q" id="(0.041666666666666664,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Me7cE9MIEe2vSZc3OuTw8Q" type="4001" element="_Me7cENMIEe2vSZc3OuTw8Q" source="_r3Lt2NMHEe2vSZc3OuTw8Q" target="_KDt94NMIEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Me8DINMIEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Me8DIdMIEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Me7cFNMIEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Me7cFdMIEe2vSZc3OuTw8Q" points="[-1, -25, 16, 617]$[-16, -635, 1, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Me8qMNMIEe2vSZc3OuTw8Q" id="(1.0,0.55)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Me8qMdMIEe2vSZc3OuTw8Q" id="(0.6,0.82)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_P3nPI9MIEe2vSZc3OuTw8Q" type="4001" element="_P3nPINMIEe2vSZc3OuTw8Q" source="_KDt94NMIEe2vSZc3OuTw8Q" target="_Oy0KQ9MIEe2vSZc3OuTw8Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_P3nPJtMIEe2vSZc3OuTw8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_P3nPJ9MIEe2vSZc3OuTw8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_P3nPJNMIEe2vSZc3OuTw8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_P3nPJdMIEe2vSZc3OuTw8Q" points="[-11, -25, 39, 100]$[-49, -111, 1, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_P3n2MNMIEe2vSZc3OuTw8Q" id="(1.0,0.5)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
